#!/bin/sh

header()
{
cat << EOF
/*
 * Automatically generated by gen-html-entities. Do not edit by hand.
 */

struct {
    char *name;
    gunichar c;
} HTMLentities[] = {
EOF
}

parse_ent_file()
{
    awk '/<!ENTITY .* CDATA/ { \
      c=substr($4,4,length($4)-5);
      print "    { \"" $2 "\", " c, "}," } \
      ' $1
}

footer()
{
cat << EOF
};
EOF
}

header
for file; do
    parse_ent_file $file
done
footer
